parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
plugins:
  - jsx-a11y
  - prettier
  - react
  - "@typescript-eslint"
extends:
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - prettier
  - prettier/react
env:
  node: true
  es6: true
globals:
  IntlRelativeFormat: false
  isNaN: false
rules:
  # Indent is owned by prettier
  "@typescript-eslint/indent": off
  react/jsx-indent: off

  # Allow explicit use of `any`
  "@typescript-eslint/no-explicit-any": off

  "@typescript-eslint/explicit-function-return-type":
    - warn
    - allowTypedFunctionExpressions: true
      allowExpressions: true

  # Single line conditionals are more difficult to set breakpoints on.
  curly:
    - error
    - all

  # Little practical value in making the distinction
  react/jsx-filename-extension: 0

  # Moving to flowtype
  react/forbid-prop-types: 0

  # We use underscores to prefix "private" class methods
  no-underscore-dangle: 0

  # babel-plugin-module-resolver aliases absolute paths to the src directory
  import/no-absolute-path: 0

  # ...
  react/destructuring-assignment: 0
  prefer-destructuring: 0
  import/prefer-default-export: 0

  # Conflicts with macros
  import/named: 0

  # Conflicts with toasts, may re-enable later
  jsx-a11y/mouse-events-have-key-events: 0
overrides:
  - files: "*.tsx"
    rules:
      react/prop-types: off
  - files: ["*.test.tsx", "*.test.js", "*.test.ts"]
    env:
      jest: true
      node: true
